// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe4ynB_A33qwg0vAhqWBkOr4vaOJAobqQ',
    appId: '1:307867785862:web:f59190f45ff2dd740c0f07',
    messagingSenderId: '307867785862',
    projectId: 'anapp-2ad07',
    authDomain: 'anapp-2ad07.firebaseapp.com',
    storageBucket: 'anapp-2ad07.firebasestorage.app',
    measurementId: 'G-M7H197D9JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUM4C9bfNIcEl4_ze1MOtyBkWt_58_lf8',
    appId: '1:307867785862:android:86ec1dd93b64d5fd0c0f07',
    messagingSenderId: '307867785862',
    projectId: 'anapp-2ad07',
    storageBucket: 'anapp-2ad07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAjWtqlPiJEinerTlqYkITM1jYZ_V23AE',
    appId: '1:307867785862:ios:547cd0dbcbab69830c0f07',
    messagingSenderId: '307867785862',
    projectId: 'anapp-2ad07',
    storageBucket: 'anapp-2ad07.firebasestorage.app',
    iosBundleId: 'com.example.anapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAjWtqlPiJEinerTlqYkITM1jYZ_V23AE',
    appId: '1:307867785862:ios:547cd0dbcbab69830c0f07',
    messagingSenderId: '307867785862',
    projectId: 'anapp-2ad07',
    storageBucket: 'anapp-2ad07.firebasestorage.app',
    iosBundleId: 'com.example.anapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe4ynB_A33qwg0vAhqWBkOr4vaOJAobqQ',
    appId: '1:307867785862:web:947792508cc5f2b00c0f07',
    messagingSenderId: '307867785862',
    projectId: 'anapp-2ad07',
    authDomain: 'anapp-2ad07.firebaseapp.com',
    storageBucket: 'anapp-2ad07.firebasestorage.app',
    measurementId: 'G-KB4TY9QMFM',
  );
}
